name: release

on:
  push:
    branches: ['release']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Builds new NetBox Docker Images
    env:
      GH_ACTION: enable
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Get Version of NetBox Docker
      run: |
        echo "::set-output name=version::$(cat VERSION)"
      shell: bash
      # ghcr.io

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      id: docker-build
      name: Build the image
      run: ./build-latest.sh --push
      env:
        DOCKER_REGISTRY: ghcr.io
        DOCKER_ORG: vseth-geco
